name: Terraform Apply Dev

on:
  push:
    branches:
      - develop
    paths:
      - 'live/dev/**'
      - 'modules/**'
      - '.github/workflows/terraform-apply-dev.yml'
      - '.github/workflows/terraform-validate-security-cost.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  apply-dev:
    runs-on: ubuntu-latest
    environment: dev
    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
    defaults:
      run:
        shell: bash
        working-directory: live/dev
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          role-session-name: github-actions-terraform-apply-dev
      - run: terraform init -backend-config=backend.hcl
      - run: terraform plan -out=tfplan
      - run: terraform apply -auto-approve tfplan
